[server]
headless = true
enableXsrfProtection = true
maxUploadSize = 200

port = 8501

[browser]
gatherUsageStats = false


[theme]
base = "light"
primaryColor = "#d62728"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#eaf5f4"
textColor = "#262730"

font = "serif"
codeFont = "monospace"
headingFont = "serif"
baseFontSize = 11
baseFontWeight = 360

dataframeHeaderBackgroundColor = "#fac62a"
showSidebarBorder = true

[theme.sidebar]
primaryColor = "#f4f1f6"
backgroundColor = "#b48649"
secondaryBackgroundColor = "#543906"
textColor = "#f6f7fc"

font = "serif"
codeFont = "monospace"
headingFont = "serif"

